export const REGION_STATS = {
  Africa:         { enacted: 8,  draft: 4,  guidelines: 3,  total: 54 },
  Europe:         { enacted: 12, draft: 5,  guidelines: 8,  total: 44 },
  'Asia-Pacific': { enacted: 6,  draft: 7,  guidelines: 4,  total: 37 },
  Americas:       { enacted: 3,  draft: 4,  guidelines: 3,  total: 35 },
  'Middle East':  { enacted: 1,  draft: 3,  guidelines: 4,  total: 14 },
};

export const COUNTRIES = [
  { name:'Namibia', region:'Africa', status:'draft', regs:['Namibia Data Protection Act (2022)','SADC AI Framework (2023)','ISO 42001:2023'], notes:"Namibia enacted comprehensive data protection legislation in 2022. AI-specific regulation is emerging through the SADC regional framework. Sector-specific rules for health and finance are under development." },
  { name:'Nigeria', region:'Africa', status:'enacted', regs:['Nigeria Data Protection Act (2023)','NITDA AI Policy Framework (2023)','FCCPC AI Guidelines'], notes:"Nigeria has a strong data protection framework through NDPA 2023, administered by the NDPC. The AI Policy Framework establishes principles for trustworthy AI." },
  { name:'Kenya', region:'Africa', status:'draft', regs:['Kenya Data Protection Act (2019)','Kenya National AI Strategy (Draft 2023)','ODPC Guidelines'], notes:"Kenya has robust data protection through the DPA 2019. A National AI Strategy is in active development. The ODPC actively enforces data rights." },
  { name:'Rwanda', region:'Africa', status:'enacted', regs:['Rwanda Data Protection Law (2021)','Rwanda National AI Policy (2023)','RURA Digital Guidelines'], notes:"Rwanda is among Africa's most advanced AI governance jurisdictions. The National AI Policy 2023 provides a clear framework aligned with Vision 2050." },
  { name:'South Africa', region:'Africa', status:'draft', regs:['POPIA (2020)','SA AI Governance Framework (Draft 2024)','FSCA AI Guidelines (Draft)'], notes:"POPIA is fully enforced. A dedicated AI Governance Framework is in public consultation. The FSCA has issued draft AI guidelines for regulated entities." },
  { name:'Ghana', region:'Africa', status:'enacted', regs:['Ghana Data Protection Act (2012, amended)','Ghana National AI Policy (2023)','GBA Digital Finance Guidelines'], notes:"Ghana has a long-standing data protection regime. The 2023 National AI Policy establishes principles for inclusive and ethical AI development." },
  { name:'Egypt', region:'Africa', status:'enacted', regs:['Egypt PDPL (2020)','Egypt National AI Strategy (2022)','Egypt Digital Health Framework'], notes:"Egypt has enacted comprehensive personal data protection and published a detailed national AI strategy with sectoral implementation roadmaps." },
  { name:'Ethiopia', region:'Africa', status:'guidelines', regs:['Ethiopia DPA (Draft 2024)','ISO 42001:2023','NIST AI RMF (default baseline)'], notes:"Ethiopia is developing its data protection legislation. International standards (ISO 42001, NIST AI RMF) constitute the responsible governance baseline." },
  { name:'Morocco', region:'Africa', status:'enacted', regs:['Morocco Law 09-08 (Data Protection)','CNDP Guidelines','Digital Morocco 2030'], notes:"Morocco has a well-established data protection framework. The Digital Morocco 2030 strategy includes AI governance pillars." },
  { name:'Mauritius', region:'Africa', status:'enacted', regs:['Mauritius Data Protection Act (2017)','Mauritius AI Strategy (2018)','FSC Guidelines'], notes:"Mauritius published Africa's first national AI strategy in 2018. The FSC has issued AI-related guidance for financial services." },
  { name:'Uganda', region:'Africa', status:'enacted', regs:['Uganda DPDPA (2019)','Uganda National AI Strategy (2023)','NITA-U Guidelines'], notes:"Uganda enacted data protection legislation in 2019. The 2023 National AI Strategy provides a forward-looking framework, with NITA-U as the implementing body." },
  { name:'Tanzania', region:'Africa', status:'guidelines', regs:['Tanzania DPA (Draft 2024)','ISO 42001:2023','NIST AI RMF (default baseline)'], notes:"Tanzania is finalising data protection legislation. International standards provide the responsible governance baseline for AI builders." },
  { name:'Senegal', region:'Africa', status:'draft', regs:['Senegal Data Protection Law (2008, revised)','ECOWAS AI Framework (Draft)','CDP Guidelines'], notes:"Senegal has an established data protection framework. ECOWAS-level AI governance discussions are ongoing." },
  { name:'Botswana', region:'Africa', status:'draft', regs:['Botswana Data Protection Act (2018)','Botswana National AI Policy (Draft 2024)'], notes:"Botswana enacted data protection in 2018. A national AI policy is in development." },
  { name:'Zimbabwe', region:'Africa', status:'guidelines', regs:['Zimbabwe Cybersecurity Act (2021)','ISO 42001:2023','NIST AI RMF (default baseline)'], notes:"Zimbabwe's Cybersecurity Act covers some AI-adjacent areas. International standards apply as baseline." },
  { name:'Tunisia', region:'Africa', status:'draft', regs:['Tunisia DPA (2004, revised)','Tunisia Digital Economy Strategy'], notes:"Tunisia has data protection in place. AI-specific regulation is under discussion within digital economy strategy development." },
  { name:'European Union', region:'Europe', status:'enacted', regs:['EU AI Act (2024)','EU GDPR (2018)','EU AI Liability Directive (Draft)'], notes:"The EU AI Act is the world's first comprehensive horizontal AI law, with obligations scaled to risk level." },
  { name:'United Kingdom', region:'Europe', status:'guidelines', regs:['UK GDPR (2021)','UK AI Regulation White Paper (2023)','ICO AI Guidance'], notes:"The UK has opted for a principles-based, sector-led approach rather than a single AI Act." },
  { name:'Germany', region:'Europe', status:'enacted', regs:['EU AI Act (2024)','Germany BDSG','Germany AI Strategy (2023)'], notes:"Germany applies the EU AI Act framework plus national BDSG data protection." },
  { name:'United States', region:'Americas', status:'guidelines', regs:['NIST AI RMF (2023)','Executive Order on AI (2023)','State-level AI Laws (multiple)'], notes:"No comprehensive federal AI law yet. The Executive Order on AI (2023) directs federal agencies to adopt NIST AI RMF." },
  { name:'Canada', region:'Americas', status:'draft', regs:['Canada AIDA (Draft 2022)','PIPEDA (2000)','OPC AI Guidance'], notes:"Canada's Artificial Intelligence and Data Act (AIDA) is pending parliamentary approval. PIPEDA governs personal data." },
  { name:'Brazil', region:'Americas', status:'draft', regs:['Brazil LGPD (2020)','Brazil AI Bill (PL 2338/2023)','Anatel AI Guidelines'], notes:"Brazil's comprehensive AI Bill is advancing through parliament. LGPD provides the existing data protection framework." },
  { name:'China', region:'Asia-Pacific', status:'enacted', regs:['China PIPL (2021)','China Generative AI Regulations (2023)','China Algorithm Recommendation Rules (2022)'], notes:"China has the most comprehensive AI-specific regulatory suite globally." },
  { name:'India', region:'Asia-Pacific', status:'draft', regs:['India DPDP Act (2023)','India AI Advisory (MeitY 2024)','SEBI AI Guidelines'], notes:"India enacted its Digital Personal Data Protection Act in 2023. A formal AI regulatory framework is expected." },
  { name:'Singapore', region:'Asia-Pacific', status:'guidelines', regs:['Singapore PDPA (2012, revised 2021)','Singapore AI Governance Framework (2020)','MAS AI Guidelines'], notes:"Singapore leads on voluntary AI governance frameworks. MAS has issued guidelines for financial sector AI." },
  { name:'Japan', region:'Asia-Pacific', status:'guidelines', regs:['Japan APPI (revised 2022)','Japan AI Guidelines (2024)','METI AI Governance'], notes:"Japan takes a principles-based, agile approach to AI regulation." },
  { name:'UAE', region:'Middle East', status:'guidelines', regs:['UAE AI Strategy 2031','UAE ADGM AI Guidance','Dubai AI Ethics Guidelines'], notes:"UAE is positioning itself as a global AI hub. Abu Dhabi Global Market (ADGM) has issued financial sector AI guidance." },
  { name:'Saudi Arabia', region:'Middle East', status:'guidelines', regs:['Saudi Arabia PDPL (2021)','SDAIA AI Ethics Principles (2022)','NDMO Data Governance'], notes:"Saudi Arabia enacted personal data protection in 2021. SDAIA has published AI ethics principles." },
];

export const STAGE_HINTS = {
  'pre-concept': 'At this stage: understand what regulations will apply so you can design for compliance from day one. Know before you build.',
  'planning': 'At this stage: document your data flows, assess risk level, and identify which obligations require design decisions now.',
  'building': 'At this stage: implement technical controls, data protection measures, and prepare required documentation.',
  'testing': 'At this stage: conduct required assessments (DPIA, conformity assessment), test for bias and fairness, and prepare audit trails.',
  'deployed': 'At this stage: monitor for drift, respond to data subject rights requests, and maintain ongoing compliance records.',
};

export const STAGE_ORDER = ['pre-concept','planning','building','testing','deployed'];

export const CDB = {
  Namibia: {
    health: { regulations: [
      { title:'Namibia Data Protection Act, 2022', status:'enacted', url:'https://www.parliament.na/acts/', obligations:[
        { id:'na-dpa-1', text:'Appoint a Data Protection Officer (DPO)', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.24', cite_text:'The responsible party must designate a data protection officer where processing is carried out on a large scale. The DPO must have expert knowledge of data protection law and practices.' },
        { id:'na-dpa-2', text:'Conduct a Data Protection Impact Assessment (DPIA) before processing health data', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.31', cite_text:'A data protection impact assessment shall be carried out prior to the processing of health data, biometric data, or data likely to result in high risk to data subjects.' },
        { id:'na-dpa-3', text:'Obtain explicit consent from patients before processing their health data', severity:'MUST', stage_from:'building', cite_ref:'Namibia DPA s.14', cite_text:'Processing of personal data concerning health shall only be permitted where the data subject has given explicit consent, or where necessary for medical diagnosis or the provision of health care.' },
        { id:'na-dpa-4', text:'Implement appropriate technical and organisational security measures', severity:'MUST', stage_from:'building', cite_ref:'Namibia DPA s.35', cite_text:'The responsible party must implement appropriate technical and organisational measures to protect personal data against accidental or unlawful destruction, loss, or unauthorised disclosure.' },
        { id:'na-dpa-5', text:'Register processing activities with the Information Regulator', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.42', cite_text:'Any person processing personal data on a large scale must notify the Information Regulator and register the processing activity.' },
        { id:'na-dpa-6', text:'Ensure data minimisation — collect only data strictly necessary for the AI purpose', severity:'SHOULD', stage_from:'planning', cite_ref:'Namibia DPA s.10', cite_text:'Personal data must be adequate, relevant, and not excessive in relation to the purpose for which it is processed.' },
        { id:'na-dpa-7', text:'Establish a data retention and deletion schedule', severity:'SHOULD', stage_from:'building', cite_ref:'Namibia DPA s.12', cite_text:'Personal data must not be retained for longer than necessary to achieve the purpose for which it was collected.' },
      ]},
      { title:'SADC AI Framework, 2023', status:'guidelines', url:'https://www.sadc.int/', obligations:[
        { id:'sadc-1', text:"Document the AI system's purpose, capabilities, and limitations in a model card", severity:'SHOULD', stage_from:'building', cite_ref:'SADC AI Framework §3.2', cite_text:'Member states are encouraged to require developers to document AI system capabilities, limitations, training data provenance, and intended use cases to enable transparency and accountability.' },
        { id:'sadc-2', text:'Implement human oversight mechanisms for AI-assisted clinical decisions', severity:'MUST', stage_from:'building', cite_ref:'SADC AI Framework §4.1', cite_text:'AI systems used in health care must maintain meaningful human oversight. Clinical decisions made with AI assistance must be reviewable and reversible by qualified health professionals.' },
        { id:'sadc-3', text:'Test for bias across gender, age, and ethnicity relevant to Namibian patient demographics', severity:'SHOULD', stage_from:'testing', cite_ref:'SADC AI Framework §5.3', cite_text:'AI systems must be evaluated for discriminatory outputs across demographic groups. Health AI must specifically address performance disparities that could result in unequal care.' },
      ]},
      { title:'ISO/IEC 42001:2023 — AI Management System', status:'standard', url:'https://www.iso.org/standard/81230.html', obligations:[
        { id:'iso-h1', text:'Establish an AI policy and assign accountability for AI governance', severity:'SHOULD', stage_from:'pre-concept', cite_ref:'ISO 42001 §5.2', cite_text:'Top management shall establish an AI policy that provides a framework for setting AI objectives and includes a commitment to responsible AI use.' },
        { id:'iso-h2', text:'Conduct AI risk assessment covering technical, ethical, and societal impacts', severity:'SHOULD', stage_from:'planning', cite_ref:'ISO 42001 §6.1', cite_text:'The organisation shall plan, implement, control, and maintain a process for AI risk assessment, including assessment of technical risks, ethical considerations, and potential impacts.' },
        { id:'iso-h3', text:'Document and control training data sources and data quality procedures', severity:'SHOULD', stage_from:'building', cite_ref:'ISO 42001 §8.4', cite_text:'The organisation shall establish controls over AI data, including data provenance, quality assessment, and handling of personal data in training datasets.' },
      ]},
    ]},
    finance: { regulations: [
      { title:'Namibia Data Protection Act, 2022', status:'enacted', url:'https://www.parliament.na/acts/', obligations:[
        { id:'na-fin-1', text:'Appoint a Data Protection Officer', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.24', cite_text:'The responsible party must designate a data protection officer where processing is carried out on a large scale.' },
        { id:'na-fin-2', text:'Implement data protection by design and by default', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.36', cite_text:'The responsible party shall implement data protection principles from the design stage of any system, process, or service.' },
        { id:'na-fin-3', text:'Provide clear disclosure when AI is used in credit or lending decisions', severity:'MUST', stage_from:'building', cite_ref:'Namibia DPA s.20', cite_text:'Where automated processing produces decisions with significant effects on a data subject, the data subject must be informed and has the right to request human review.' },
        { id:'na-fin-4', text:'Implement mechanisms for customers to contest automated financial decisions', severity:'MUST', stage_from:'building', cite_ref:'Namibia DPA s.21', cite_text:'Data subjects must have the right to request that any decision subject to automated processing be reconsidered by a human reviewer.' },
      ]},
    ]},
    general: { regulations: [
      { title:'Namibia Data Protection Act, 2022', status:'enacted', url:'https://www.parliament.na/acts/', obligations:[
        { id:'na-gen-1', text:'Register processing activities with the Information Regulator', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.42', cite_text:'Any person processing personal data on a large scale must notify the Information Regulator and register the processing activity.' },
        { id:'na-gen-2', text:'Implement lawful basis for all data processing', severity:'MUST', stage_from:'planning', cite_ref:'Namibia DPA s.8', cite_text:'Personal data may only be processed if a lawful basis exists: consent, contract, legal obligation, vital interests, public task, or legitimate interests.' },
        { id:'na-gen-3', text:'Respect data subject rights: access, correction, deletion, objection', severity:'MUST', stage_from:'building', cite_ref:'Namibia DPA s.17-23', cite_text:'Data subjects have the right to access their personal data, have inaccurate data corrected, request deletion, and object to certain processing.' },
      ]},
    ]},
  },
  Nigeria: {
    health: { regulations: [
      { title:'Nigeria Data Protection Act, 2023', status:'enacted', url:'https://ndpc.gov.ng/', obligations:[
        { id:'ng-h1', text:'Conduct mandatory DPIA for health AI', severity:'MUST', stage_from:'planning', cite_ref:'Nigeria NDPA s.28', cite_text:'A data controller conducting processing likely to result in high risk to the rights and freedoms of data subjects must carry out a data protection impact assessment prior to the processing.' },
        { id:'ng-h2', text:'Register as a data controller with the NDPC', severity:'MUST', stage_from:'planning', cite_ref:'Nigeria NDPA s.32', cite_text:'A data controller of major importance must register with the Commission not later than six months after the commencement of this Act.' },
        { id:'ng-h3', text:'Obtain explicit consent for processing health data', severity:'MUST', stage_from:'building', cite_ref:'Nigeria NDPA s.25(2)', cite_text:'The processing of sensitive personal data shall be prohibited unless the data subject has given explicit consent to the processing of that personal data for one or more specified purposes.' },
        { id:'ng-h4', text:'Appoint a Data Protection Compliance Organisation (DPCO)', severity:'SHOULD', stage_from:'planning', cite_ref:'Nigeria NDPA s.34', cite_text:'A data controller may engage a data protection compliance organisation to advise on compliance with this Act.' },
      ]},
      { title:'NITDA AI Policy Framework, 2023', status:'guidelines', url:'https://nitda.gov.ng/', obligations:[
        { id:'nitda-1', text:'Document AI system transparency disclosures for end users', severity:'SHOULD', stage_from:'building', cite_ref:'NITDA AI Framework §6.1', cite_text:"AI systems deployed in Nigeria must provide clear disclosure of their AI nature to users, explain how decisions are made in accessible language, and enable users to seek human review." },
        { id:'nitda-2', text:'Implement bias testing relevant to Nigerian demographic diversity', severity:'SHOULD', stage_from:'testing', cite_ref:'NITDA AI Framework §7.3', cite_text:"Developers must conduct fairness testing across Nigeria's diverse demographic groups, including gender, ethnicity, language, and socioeconomic status." },
      ]},
    ]},
    general: { regulations: [
      { title:'Nigeria Data Protection Act, 2023', status:'enacted', url:'https://ndpc.gov.ng/', obligations:[
        { id:'ng-g1', text:'Register with NDPC as data controller', severity:'MUST', stage_from:'planning', cite_ref:'Nigeria NDPA s.32', cite_text:'A data controller of major importance must register with the Commission not later than six months after the commencement of this Act.' },
        { id:'ng-g2', text:'Implement lawful basis for all personal data processing', severity:'MUST', stage_from:'planning', cite_ref:'Nigeria NDPA s.25', cite_text:'The processing of personal data shall be lawful only if based on consent, contract, legal obligation, vital interests, public task, or legitimate interests.' },
        { id:'ng-g3', text:'Establish data subject rights procedures (access, correction, erasure)', severity:'MUST', stage_from:'building', cite_ref:'Nigeria NDPA s.35-42', cite_text:'Data subjects have the right to access personal data, rectify inaccurate data, and in certain circumstances, erase their data. Controllers must respond within 30 days.' },
      ]},
    ]},
  },
  'European Union': {
    health: { regulations: [
      { title:'EU AI Act, 2024', status:'enacted', url:'https://artificialintelligenceact.eu/', obligations:[
        { id:'euai-h1', text:'Classify your AI system — health diagnostic AI is likely HIGH RISK', severity:'MUST', stage_from:'pre-concept', cite_ref:'EU AI Act Annex III', cite_text:'AI systems intended to be used for medical devices, or AI intended to be used for making decisions in the context of health and safety of persons, are classified as high-risk AI systems under Annex III.' },
        { id:'euai-h2', text:'Register high-risk AI system in the EU AI Act database before deployment', severity:'MUST', stage_from:'testing', cite_ref:'EU AI Act Art. 71', cite_text:'Providers of high-risk AI systems shall register themselves and their systems in the EU database before placing the system on the market.' },
        { id:'euai-h3', text:'Prepare technical documentation demonstrating compliance', severity:'MUST', stage_from:'building', cite_ref:'EU AI Act Art. 11', cite_text:'Providers of high-risk AI systems shall draw up technical documentation before placing that system on the market.' },
        { id:'euai-h4', text:'Implement a post-market monitoring system', severity:'MUST', stage_from:'deployed', cite_ref:'EU AI Act Art. 72', cite_text:'Providers of high-risk AI systems shall establish and document a post-market monitoring system appropriate to the nature of the AI technology.' },
        { id:'euai-h5', text:'Conduct conformity assessment (self-assessment or third party)', severity:'MUST', stage_from:'testing', cite_ref:'EU AI Act Art. 43', cite_text:'High-risk AI systems shall undergo a conformity assessment procedure before being placed on the market. For medical AI, third-party conformity assessment is required.' },
        { id:'euai-h6', text:'Appoint an EU representative if deploying from outside the EU', severity:'MUST', stage_from:'planning', cite_ref:'EU AI Act Art. 22', cite_text:'Where neither the provider nor the importer is established in the Union, providers shall designate an authorised representative established in the Union.' },
      ]},
      { title:'EU GDPR, 2018', status:'enacted', url:'https://gdpr-info.eu/', obligations:[
        { id:'gdpr-h1', text:'Conduct DPIA before processing health data at scale', severity:'MUST', stage_from:'planning', cite_ref:'GDPR Art. 35', cite_text:'Where processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall carry out an assessment of the impact on the protection of personal data prior to processing.' },
        { id:'gdpr-h2', text:'Identify lawful basis for processing special category health data', severity:'MUST', stage_from:'planning', cite_ref:'GDPR Art. 9', cite_text:'Processing of personal data concerning health shall be prohibited unless the data subject has given explicit consent, or processing is necessary for medical purposes.' },
      ]},
    ]},
    general: { regulations: [
      { title:'EU AI Act, 2024', status:'enacted', url:'https://artificialintelligenceact.eu/', obligations:[
        { id:'euai-g1', text:'Classify your AI system under EU AI Act risk framework', severity:'MUST', stage_from:'pre-concept', cite_ref:'EU AI Act Art. 6', cite_text:'AI systems shall be classified as high-risk where they are listed in Annex III or intended as a safety component of a product covered by Union harmonisation legislation.' },
        { id:'euai-g2', text:'Ensure prohibited AI practices are not used (social scoring, manipulation, etc.)', severity:'MUST', stage_from:'pre-concept', cite_ref:'EU AI Act Art. 5', cite_text:'The following AI practices shall be prohibited: AI systems using subliminal techniques, AI systems enabling social scoring by public authorities, real-time biometric identification in public spaces.' },
        { id:'euai-g3', text:'Implement human oversight measures for high-risk AI', severity:'MUST', stage_from:'building', cite_ref:'EU AI Act Art. 14', cite_text:'High-risk AI systems shall be designed and developed in such a way as to allow human oversight during the period in which the AI system is in use.' },
      ]},
    ]},
  },
  'South Africa': {
    health: { regulations: [
      { title:'POPIA, 2020', status:'enacted', url:'https://popia.co.za/', obligations:[
        { id:'sa-h1', text:'Appoint an Information Officer and register with the Information Regulator', severity:'MUST', stage_from:'planning', cite_ref:'POPIA s.55', cite_text:'The head of a private or public body must be the Information Officer of that body. The Information Officer must be registered with the Information Regulator.' },
        { id:'sa-h2', text:'Process health data only with explicit consent or lawful basis', severity:'MUST', stage_from:'building', cite_ref:'POPIA s.27', cite_text:'The processing of special personal information, including health data, is prohibited unless the data subject has given explicit consent or processing is necessary for medical purposes.' },
        { id:'sa-h3', text:'Notify the Regulator and data subjects of security compromises', severity:'MUST', stage_from:'deployed', cite_ref:'POPIA s.22', cite_text:'Where there are reasonable grounds to believe that personal information has been accessed by any unauthorised person, the responsible party must notify the Regulator and the data subject.' },
      ]},
      { title:'SA AI Governance Framework (Draft 2024)', status:'draft', url:'https://www.dsit.gov.za/', obligations:[
        { id:'sa-ai-1', text:'Implement transparency requirements for AI-assisted clinical decisions', severity:'SHOULD', stage_from:'building', cite_ref:'SA AI Framework §4.2', cite_text:"AI systems used in health care should make their use transparent to patients and clinicians." },
        { id:'sa-ai-2', text:"Assess AI system for bias across South Africa's demographic groups", severity:'SHOULD', stage_from:'testing', cite_ref:'SA AI Framework §5.1', cite_text:"AI developers are encouraged to evaluate systems for differential performance across South Africa's diverse population." },
      ]},
    ]},
    general: { regulations: [
      { title:'POPIA, 2020', status:'enacted', url:'https://popia.co.za/', obligations:[
        { id:'sa-g1', text:'Appoint Information Officer and register with Information Regulator', severity:'MUST', stage_from:'planning', cite_ref:'POPIA s.55', cite_text:'The head of a private or public body must be the Information Officer. Must be registered with the Information Regulator.' },
        { id:'sa-g2', text:'Apply all eight POPIA conditions for lawful processing', severity:'MUST', stage_from:'building', cite_ref:'POPIA s.4', cite_text:'Personal information must be processed lawfully and in a reasonable manner that does not infringe privacy. The eight conditions for lawful processing must all be satisfied.' },
      ]},
    ]},
  },
  Kenya: {
    health: { regulations: [
      { title:'Kenya Data Protection Act, 2019', status:'enacted', url:'https://www.odpc.go.ke/', obligations:[
        { id:'ke-h1', text:'Register as a data controller / processor with the ODPC', severity:'MUST', stage_from:'planning', cite_ref:'Kenya DPA s.17', cite_text:'Every data controller or data processor shall register with the Data Commissioner. Processing without registration is an offence.' },
        { id:'ke-h2', text:'Conduct DPIA for health data processing', severity:'MUST', stage_from:'planning', cite_ref:'Kenya DPA s.31', cite_text:'A data controller shall carry out a data protection impact assessment where the processing is likely to result in a high risk to the rights and freedoms of the data subjects.' },
        { id:'ke-h3', text:'Obtain explicit consent for health data processing', severity:'MUST', stage_from:'building', cite_ref:'Kenya DPA s.30(2)', cite_text:'The processing of sensitive personal data shall only be permitted if the data subject has given explicit consent to the processing.' },
      ]},
    ]},
    general: { regulations: [
      { title:'Kenya Data Protection Act, 2019', status:'enacted', url:'https://www.odpc.go.ke/', obligations:[
        { id:'ke-g1', text:'Register with ODPC as data controller or processor', severity:'MUST', stage_from:'planning', cite_ref:'Kenya DPA s.17', cite_text:'Every data controller or data processor shall register with the Data Commissioner.' },
        { id:'ke-g2', text:'Establish lawful basis for all personal data processing', severity:'MUST', stage_from:'planning', cite_ref:'Kenya DPA s.30', cite_text:'Processing shall be lawful only if the data subject has given consent, processing is necessary for a contract, or another lawful basis applies.' },
      ]},
    ]},
  },
  default: {
    general: { regulations: [
      { title:'ISO/IEC 42001:2023 — AI Management System', status:'standard', url:'https://www.iso.org/standard/81230.html', obligations:[
        { id:'def-iso-1', text:'Establish an AI governance policy and assign top-level accountability', severity:'SHOULD', stage_from:'pre-concept', cite_ref:'ISO 42001 §5.2', cite_text:'Top management shall establish an AI policy providing a framework for setting AI objectives and includes a commitment to responsible AI use.' },
        { id:'def-iso-2', text:'Conduct AI risk assessment covering technical, ethical, and societal impacts', severity:'SHOULD', stage_from:'planning', cite_ref:'ISO 42001 §6.1', cite_text:'The organisation shall plan, implement, control, and maintain a process for AI risk assessment, including assessment of technical risks, ethical considerations, and potential impacts.' },
        { id:'def-iso-3', text:'Document and control training data sources and quality procedures', severity:'SHOULD', stage_from:'building', cite_ref:'ISO 42001 §8.4', cite_text:'The organisation shall establish controls over AI data, including data provenance, quality assessment, and handling of personal data in training datasets.' },
        { id:'def-iso-4', text:'Monitor AI system performance post-deployment', severity:'SHOULD', stage_from:'deployed', cite_ref:'ISO 42001 §9.1', cite_text:'The organisation shall evaluate AI system performance, including monitoring for model drift, unintended outputs, and changes in the data environment.' },
      ]},
      { title:'NIST AI Risk Management Framework (AI RMF 1.0)', status:'standard', url:'https://www.nist.gov/system/files/documents/2023/01/26/AI%20RMF%201.0.pdf', obligations:[
        { id:'def-nist-1', text:'MAP: Identify stakeholders, assess context, document use cases and potential impacts', severity:'SHOULD', stage_from:'pre-concept', cite_ref:'NIST AI RMF — MAP', cite_text:'The MAP function involves understanding the context, purpose, and potential impacts of the AI system, including identification of all relevant stakeholders and their interests.' },
        { id:'def-nist-2', text:'MEASURE: Test and evaluate AI risks through red-teaming and bias assessment', severity:'SHOULD', stage_from:'testing', cite_ref:'NIST AI RMF — MEASURE', cite_text:'The MEASURE function involves quantifying AI risks and impacts through evaluation, testing, and monitoring, including assessing for bias and performance disparities.' },
        { id:'def-nist-3', text:'MANAGE: Prioritise and document risk response plans', severity:'SHOULD', stage_from:'planning', cite_ref:'NIST AI RMF — MANAGE', cite_text:'The MANAGE function involves prioritising identified risks and implementing responses, including mitigations, transfer, or acceptance, with documented rationale.' },
      ]},
    ]},
  },
};

export const LIBRARY = [
  {
    name: 'EU AI Act',
    country: 'European Union',
    region: 'Europe',
    year: 2024,
    status: 'enacted',
    themes: ['AI regulation', 'High-risk AI', 'Transparency', 'Human oversight'],
    url: 'https://artificialintelligenceact.eu/',
    summary: `The EU AI Act is the world's first comprehensive, binding AI law. It establishes a risk-based framework that classifies AI systems into four tiers: unacceptable risk (banned outright), high risk (strict obligations), limited risk (transparency requirements), and minimal risk (no obligations). High-risk AI systems — including those used in healthcare, education, employment, and critical infrastructure — must undergo conformity assessments, maintain technical documentation, implement human oversight, and register in an EU database before deployment. The Act also introduces specific rules for General Purpose AI (GPAI) models, including foundation models and large language models, requiring transparency about training data and capabilities. For African AI builders targeting European markets, the Act applies extraterritorially — if your AI system is deployed in the EU or affects EU users, you are subject to its obligations regardless of where you are based.`,
    keyProvisions: [
      'Prohibited AI practices (Art. 5): social scoring, subliminal manipulation, real-time biometric surveillance in public spaces',
      'High-risk AI classification (Annex III): health, education, employment, critical infrastructure, law enforcement',
      'Conformity assessment required before market placement for high-risk systems',
      'GPAI model obligations from August 2025: transparency, copyright compliance, systemic risk assessment',
      'Right of individuals to explanation for high-risk AI decisions affecting them',
      'Fines up to €35 million or 7% of global turnover for prohibited practice violations',
    ],
    appliesTo: 'Any organisation placing AI systems on the EU market or deploying AI systems that affect EU users, regardless of where the organisation is based.',
  },
  {
    name: 'EU GDPR',
    country: 'European Union',
    region: 'Europe',
    year: 2018,
    status: 'enacted',
    themes: ['Data protection', 'Privacy', 'Consent', 'Data subject rights'],
    url: 'https://gdpr-info.eu/',
    summary: `The General Data Protection Regulation (GDPR) is the foundational EU data protection law that governs how personal data of EU residents may be collected, processed, and stored. For AI systems, GDPR has direct and critical implications: it restricts automated decision-making that produces legal or similarly significant effects on individuals (Article 22), requires a lawful basis for all processing, mandates Data Protection Impact Assessments (DPIAs) for high-risk processing, and imposes strict rules on processing special category data including health, biometric, and genetic data. Any AI system that processes personal data of EU residents — including through APIs, SaaS products, or embedded features — must comply with GDPR regardless of where the AI provider is based.`,
    keyProvisions: [
      'Lawful basis for processing (Art. 6): consent, contract, legal obligation, vital interests, public task, legitimate interests',
      'Special category data (Art. 9): health, biometric, genetic data requires explicit consent or specific legal basis',
      'Data Protection Impact Assessment (Art. 35): mandatory for high-risk processing including large-scale health data',
      'Automated decision-making (Art. 22): right not to be subject to solely automated decisions with significant effects',
      'Data subject rights: access, rectification, erasure, portability, objection',
      'Data Protection Officer required for large-scale processing of special category data',
    ],
    appliesTo: 'Any organisation processing personal data of individuals in the EU, regardless of where the organisation is established.',
  },
  {
    name: 'Namibia Data Protection Act',
    country: 'Namibia',
    region: 'Africa',
    year: 2022,
    status: 'enacted',
    themes: ['Data protection', 'Health data', 'DPO', 'DPIA'],
    url: 'https://www.parliament.na/acts/',
    summary: `Namibia's Data Protection Act (2022) is a comprehensive data protection law modelled closely on the GDPR. It establishes the rights of data subjects and the obligations of responsible parties (data controllers) and operators (data processors). For AI builders operating in Namibia or processing data of Namibian residents, the Act imposes registration requirements, mandates Data Protection Officers for large-scale processing, requires Data Protection Impact Assessments for high-risk activities including health data processing, and grants individuals rights to access, correct, and delete their personal data. The Act established an Information Regulator as the enforcement authority. Non-compliance can result in significant fines and criminal liability.`,
    keyProvisions: [
      'Registration of processing activities with the Information Regulator (s.42)',
      'Mandatory DPO appointment for large-scale processing (s.24)',
      'DPIA required before processing health or biometric data (s.31)',
      'Explicit consent required for health data processing (s.14)',
      'Data minimisation and purpose limitation principles (s.10-11)',
      'Security measures must be implemented against unauthorised access (s.35)',
      'Data subject rights: access, correction, deletion, objection (s.17-23)',
    ],
    appliesTo: 'Any person or organisation processing personal data in Namibia or processing personal data of Namibian residents.',
  },
  {
    name: 'Nigeria Data Protection Act',
    country: 'Nigeria',
    region: 'Africa',
    year: 2023,
    status: 'enacted',
    themes: ['Data protection', 'Consent', 'DPIA', 'Registration'],
    url: 'https://ndpc.gov.ng/',
    summary: `Nigeria's Data Protection Act (NDPA) 2023 is the country's landmark data protection legislation, establishing the Nigeria Data Protection Commission (NDPC) as regulator. It replaced the earlier NDPR framework and significantly strengthened protections for personal data. For AI builders, key implications include mandatory registration with the NDPC for data controllers of major importance, strict rules on processing sensitive personal data including health information, requirements for Data Protection Impact Assessments for high-risk processing, and the option to engage a licensed Data Protection Compliance Organisation (DPCO) to assist with compliance. The Act applies extraterritorially — any organisation processing data of Nigerian residents must comply regardless of where it is based.`,
    keyProvisions: [
      'Nigeria Data Protection Commission (NDPC) established as independent regulator',
      'Data controllers of major importance must register within 6 months (s.32)',
      'Sensitive personal data processing requires explicit consent (s.25)',
      'DPIA mandatory for high-risk processing (s.28)',
      'Data subject rights: access, rectification, erasure, restriction, portability',
      'Cross-border transfer restrictions — adequate protection required in destination country',
      'Administrative fines up to 2% of annual gross revenue or ₦10 million (whichever is higher)',
    ],
    appliesTo: 'Any organisation processing personal data of individuals in Nigeria, whether the organisation is based in Nigeria or overseas.',
  },
  {
    name: 'Kenya Data Protection Act',
    country: 'Kenya',
    region: 'Africa',
    year: 2019,
    status: 'enacted',
    themes: ['Data protection', 'Registration', 'DPIA', 'Sensitive data'],
    url: 'https://www.odpc.go.ke/',
    summary: `Kenya's Data Protection Act (2019) established the Office of the Data Protection Commissioner (ODPC) and created a comprehensive framework for data protection rights and obligations. It was one of the first dedicated data protection laws in East Africa. For AI builders, the Act requires registration with the ODPC for all data controllers and processors, mandates Data Protection Impact Assessments for high-risk processing, imposes strict rules on processing sensitive personal data (including health, biometric, and financial data), and grants data subjects a range of rights. The ODPC has been actively enforcing the Act since 2021, issuing enforcement notices and fines for non-compliance.`,
    keyProvisions: [
      'Mandatory registration of all data controllers and processors with the ODPC (s.17)',
      'DPIA required for high-risk processing activities (s.31)',
      'Explicit consent required for sensitive personal data including health data (s.30)',
      'Data subject rights: access, rectification, erasure, restriction, objection',
      'Data localisation considerations for certain categories of data',
      'Cross-border transfer rules: adequate protection required in destination',
      'Fines up to KES 5 million or imprisonment for serious violations',
    ],
    appliesTo: 'Any data controller or processor handling personal data of individuals in Kenya.',
  },
  {
    name: 'South Africa POPIA',
    country: 'South Africa',
    region: 'Africa',
    year: 2020,
    status: 'enacted',
    themes: ['Data protection', 'Information Officer', 'Special data'],
    url: 'https://popia.co.za/',
    summary: `The Protection of Personal Information Act (POPIA) is South Africa's comprehensive data protection law, enforced by the Information Regulator. It came into full effect in July 2021. POPIA establishes eight conditions for lawful processing of personal information and imposes strict rules on processing special personal information including health data, biometric data, and data concerning children. For AI builders, POPIA requires appointment and registration of an Information Officer, imposes security safeguards obligations, restricts automated decision-making that significantly affects data subjects, and grants individuals rights to access and correct their personal information. The Information Regulator has shown increasing willingness to enforce POPIA, including issuing enforcement notices to major South African organisations.`,
    keyProvisions: [
      'Eight conditions for lawful processing: accountability, processing limitation, purpose specification, further processing limitation, information quality, openness, security safeguards, data subject participation',
      'Information Officer must be appointed and registered with the Information Regulator (s.55)',
      'Special personal information (health, biometric, children\'s data) requires explicit consent or specific legal basis (s.27)',
      'Security breach notification to the Regulator and affected data subjects (s.22)',
      'Automated decision-making restrictions — data subjects may request human review (s.71)',
      'Data subject rights: access, correction, deletion (s.23-25)',
      'Fines up to R10 million and/or imprisonment for serious violations',
    ],
    appliesTo: 'Any public or private body that processes personal information of South African residents, including organisations based outside South Africa that process such data.',
  },
  {
    name: 'Rwanda National AI Policy',
    country: 'Rwanda',
    region: 'Africa',
    year: 2023,
    status: 'enacted',
    themes: ['AI strategy', 'Governance', 'Innovation'],
    url: 'https://www.minict.gov.rw/',
    summary: `Rwanda's National AI Policy (2023) positions Rwanda as a leading AI governance jurisdiction in Africa. It establishes a comprehensive framework for responsible AI development and deployment aligned with Rwanda's Vision 2050 development goals. The policy emphasises trustworthy AI, inclusive innovation, and digital sovereignty. It creates governance structures for AI oversight, establishes principles for ethical AI (transparency, fairness, accountability, privacy, safety), and outlines sectoral priorities including agriculture, health, education, and public services. Rwanda is notable for combining both data protection law (DPL 2021) and AI-specific policy, making it one of the most complete regulatory environments in Africa for AI builders.`,
    keyProvisions: [
      'National AI governance structure with designated regulatory responsibilities',
      'Six AI principles: transparency, fairness, accountability, privacy, safety, inclusivity',
      'Sectoral AI roadmaps for health, agriculture, education, and public services',
      'Mandatory AI impact assessments for high-risk government AI deployments',
      'AI skills development and local capacity building requirements',
      'Data sovereignty and localisation considerations for sensitive data',
    ],
    appliesTo: 'AI developers and deployers operating in Rwanda or building AI systems intended for Rwandan users or government applications.',
  },
  {
    name: 'SA AI Governance Framework (Draft)',
    country: 'South Africa',
    region: 'Africa',
    year: 2024,
    status: 'draft',
    themes: ['AI regulation', 'Transparency', 'Bias', 'Ethics'],
    url: 'https://www.dsit.gov.za/',
    summary: `South Africa's Draft AI Governance Framework (2024) is currently in public consultation and represents the country's first dedicated AI regulatory instrument. It complements POPIA with AI-specific requirements including algorithmic impact assessments, transparency obligations for AI-assisted decisions, human oversight requirements for high-impact AI, and fairness testing across South Africa's diverse demographic groups. The framework takes a risk-based approach, with stricter obligations for AI systems used in consequential domains including healthcare, financial services, employment, and criminal justice. It is expected to be finalised in 2025 and will likely become binding regulation for certain AI use cases.`,
    keyProvisions: [
      'Risk-based classification of AI systems by potential impact',
      'Algorithmic Impact Assessments required for high-impact AI deployments',
      'Transparency obligations: users must be informed when AI is used in consequential decisions',
      'Human oversight requirements: AI-assisted decisions in high-impact domains must be reviewable',
      'Fairness testing across race, gender, language, and socioeconomic groups',
      'Accountability requirements: clear responsibility chains for AI system outcomes',
    ],
    appliesTo: 'Organisations developing or deploying AI systems in South Africa, with particular focus on high-impact sectors including health, finance, employment, and public services.',
  },
  {
    name: 'ISO/IEC 42001:2023',
    country: 'International',
    region: 'International',
    year: 2023,
    status: 'standard',
    themes: ['AI management', 'Risk', 'Governance', 'Certification'],
    url: 'https://www.iso.org/standard/81230.html',
    summary: `ISO/IEC 42001:2023 is the international standard for AI Management Systems (AIMS). It is the AI equivalent of ISO 27001 for information security — providing a systematic framework for organisations to responsibly develop, provide, or use AI systems. The standard specifies requirements for establishing, implementing, maintaining, and continually improving an AI management system within the context of an organisation. It covers AI risk management, impact assessment, data governance, transparency, and human oversight. ISO 42001 certification is increasingly required by enterprise customers and government procurement processes globally, making it a significant competitive advantage for AI builders — especially those targeting B2B markets in regulated industries. For African AI builders operating in jurisdictions without specific AI laws, ISO 42001 provides the internationally recognised baseline for responsible AI governance.`,
    keyProvisions: [
      'AI policy and top management commitment (§5.2)',
      'AI risk assessment and treatment process (§6.1)',
      'AI objectives and planning to achieve them (§6.2)',
      'AI data management and quality controls (§8.4)',
      'AI system impact assessment process (§8.5)',
      'Performance evaluation and monitoring (§9.1)',
      'Continual improvement of the AI management system (§10)',
    ],
    appliesTo: 'Any organisation that develops, provides, or uses AI systems — regardless of size, sector, or jurisdiction. Particularly valuable in jurisdictions without specific AI legislation.',
  },
  {
    name: 'NIST AI Risk Management Framework',
    country: 'International',
    region: 'International',
    year: 2023,
    status: 'standard',
    themes: ['AI risk', 'GOVERN', 'MAP', 'MEASURE', 'MANAGE'],
    url: 'https://www.nist.gov/system/files/documents/2023/01/26/AI%20RMF%201.0.pdf',
    summary: `The NIST AI Risk Management Framework (AI RMF 1.0) is a voluntary framework developed by the US National Institute of Standards and Technology to help organisations manage AI-related risks. It is organised around four core functions: GOVERN (establishing organisational practices for AI risk management), MAP (identifying and categorising AI risks in context), MEASURE (analysing and assessing AI risks), and MANAGE (prioritising and treating AI risks). The AI RMF is referenced in the US Executive Order on AI and by regulators globally including in the EU. It provides practical, actionable guidance for AI builders at any stage of development, making it particularly useful for organisations in jurisdictions without binding AI-specific legislation. It is freely available and widely adopted across sectors.`,
    keyProvisions: [
      'GOVERN: organisational policies, culture, and accountability for AI risk',
      'MAP: AI system context, categorisation, and stakeholder identification',
      'MEASURE: risk analysis, evaluation, and monitoring methodologies',
      'MANAGE: risk response, treatment, and residual risk acceptance',
      'AI Trustworthiness characteristics: valid, reliable, safe, secure, explainable, privacy-enhanced, fair, accountable, transparent',
      'Profiles and tiers for tailoring the framework to organisational context',
    ],
    appliesTo: 'Any organisation developing, deploying, or procuring AI systems. Particularly useful as a baseline governance framework in jurisdictions without binding AI-specific legislation.',
  },
  {
    name: 'NITDA AI Policy Framework',
    country: 'Nigeria',
    region: 'Africa',
    year: 2023,
    status: 'guidelines',
    themes: ['AI governance', 'Transparency', 'Fairness'],
    url: 'https://nitda.gov.ng/',
    summary: `Nigeria's AI Policy Framework (2023), issued by the National Information Technology Development Agency (NITDA), establishes principles and guidelines for trustworthy AI development and deployment in Nigeria. It complements the NDPA 2023 with AI-specific guidance on transparency, fairness, accountability, and human oversight. The framework emphasises the need for AI systems deployed in Nigeria to be explainable to users, to be tested for bias across Nigeria's diverse demographic groups, and to maintain meaningful human oversight in high-stakes decisions. While currently guidelines rather than binding law, NITDA has signalled intent to strengthen enforcement and move toward binding AI-specific regulation.`,
    keyProvisions: [
      'Seven AI principles: transparency, fairness, accountability, safety, privacy, inclusivity, sustainability',
      'Transparency disclosures required for AI-assisted decisions (§6.1)',
      'Bias testing across gender, ethnicity, language, and socioeconomic groups (§7.3)',
      'Human oversight requirements for high-stakes AI applications',
      'AI impact assessments recommended for significant deployments',
      'Sector-specific guidance for financial services, health, and public sector AI',
    ],
    appliesTo: 'Organisations developing or deploying AI systems in Nigeria, particularly in regulated sectors including financial services, healthcare, and public administration.',
  },
  {
    name: 'SADC AI Framework',
    country: 'Regional (SADC)',
    region: 'Africa',
    year: 2023,
    status: 'guidelines',
    themes: ['Regional AI', 'Health AI', 'Human oversight', 'Southern Africa'],
    url: 'https://www.sadc.int/',
    summary: `The Southern African Development Community (SADC) AI Framework (2023) provides regional guidance for responsible AI adoption across SADC member states including South Africa, Namibia, Botswana, Zimbabwe, Tanzania, and 12 other countries. It is particularly relevant for AI builders targeting multiple Southern African markets simultaneously, as it provides a common baseline that informs national AI governance approaches across the region. The framework emphasises AI for development, with particular focus on agricultural AI, health AI, and AI for public services. It strongly emphasises human oversight for AI in high-stakes domains, documentation requirements, and demographic fairness testing relevant to Southern African populations.`,
    keyProvisions: [
      'Regional AI governance coordination among SADC member states',
      'Documentation requirements for AI systems: model cards, system cards (§3.2)',
      'Mandatory human oversight for AI in healthcare and justice (§4.1)',
      'Fairness testing across Southern African demographic groups (§5.3)',
      'Data sovereignty principles for cross-border AI data flows',
      'AI capacity building and skills development priorities',
    ],
    appliesTo: 'Organisations deploying AI systems in SADC member states, particularly those operating across multiple Southern African markets.',
  },
  {
    name: 'Canada AIDA',
    country: 'Canada',
    region: 'Americas',
    year: 2022,
    status: 'draft',
    themes: ['AI regulation', 'High-impact AI', 'Accountability'],
    url: 'https://ised-isde.canada.ca/site/innovation-better-canada/en/artificial-intelligence-and-data-act',
    summary: `Canada's Artificial Intelligence and Data Act (AIDA) is proposed legislation that would be the first comprehensive AI law in the Americas. It establishes obligations for organisations that design, develop, or deploy "high-impact AI systems" — those that make automated decisions affecting individuals in significant ways. AIDA requires impact assessments, risk mitigation measures, transparency obligations, and incident reporting for high-impact AI. It also introduces prohibitions on AI systems that pose serious risks to health, safety, or fundamental rights. AIDA is currently progressing through the Canadian parliament and, if enacted, would apply to AI systems used in regulated industries and in interactions with Canadians.`,
    keyProvisions: [
      'High-impact AI system classification based on potential for harm',
      'Mandatory impact assessments for high-impact AI systems',
      'Risk mitigation measures and monitoring requirements',
      'Transparency: plain-language explanation of AI decision-making',
      'Incident reporting to the AI and Data Commissioner',
      'Prohibitions on AI that poses serious risk to health, safety, or rights',
      'Fines up to CAD $25 million or 5% of global revenue',
    ],
    appliesTo: 'Organisations in Canada or those deploying AI systems affecting Canadians in high-impact contexts, particularly in federally regulated industries.',
  },
  {
    name: 'China Generative AI Regulations',
    country: 'China',
    region: 'Asia-Pacific',
    year: 2023,
    status: 'enacted',
    themes: ['Generative AI', 'Content labelling', 'AIGC'],
    url: 'https://www.cac.gov.cn/',
    summary: `China's Interim Measures for the Management of Generative Artificial Intelligence Services (2023) are the world's first binding regulations specifically targeting generative AI. Issued by the Cyberspace Administration of China (CAC), they apply to any organisation providing generative AI services to users in China — including text, image, audio, video, and code generation. Key requirements include security assessments before launch for services with significant public opinion influence, content labelling to identify AI-generated content, registration with the CAC, training data compliance (copyright and personal data), and mechanisms to prevent the generation of prohibited content. These regulations apply extraterritorially to overseas services accessible in China.`,
    keyProvisions: [
      'Security assessment required before launch for significant generative AI services',
      'AI-generated content must be labelled (watermarking or metadata)',
      'Registration with the CAC for services meeting threshold criteria',
      'Training data must comply with copyright law and personal information protection',
      'Mechanisms to prevent generation of prohibited content (political, harmful, illegal)',
      'User complaint and redress mechanisms required',
      'Real-name registration for users of certain generative AI services',
    ],
    appliesTo: 'Any organisation providing generative AI services to users in China, including overseas providers whose services are accessible in China.',
  },
  {
    name: 'Singapore AI Governance Framework',
    country: 'Singapore',
    region: 'Asia-Pacific',
    year: 2020,
    status: 'guidelines',
    themes: ['AI governance', 'Transparency', 'Human oversight', 'Explainability'],
    url: 'https://www.imda.gov.sg/resources/publications/AI-Governance-Framework',
    summary: `Singapore's Model AI Governance Framework (2020, updated) is one of the most practically useful voluntary AI governance frameworks globally. Developed by the Infocomm Media Development Authority (IMDA), it provides detailed, sector-agnostic guidance for organisations deploying AI responsibly. The framework is structured around two key principles: decisions made by AI should be explainable, transparent, and fair; and AI systems should be human-centric — with meaningful human oversight especially in high-stakes contexts. It includes an Implementation and Self-Assessment Guide (ISAGO) that allows organisations to assess their AI governance maturity. Singapore's approach is deliberately non-prescriptive, allowing industry flexibility while setting clear expectations.`,
    keyProvisions: [
      'Human involvement in AI-augmented decision-making: proportional to risk level',
      'Explainability: AI decisions must be explainable to affected individuals',
      'Operations management: AI system monitoring, testing, and incident management',
      'Customer relationship management: transparency with users about AI use',
      'Data governance: quality, bias assessment, and lineage tracking',
      'Self-assessment guide (ISAGO) for governance maturity evaluation',
    ],
    appliesTo: 'Organisations deploying AI systems in Singapore across all sectors. Particularly referenced by MAS for financial sector AI.',
  },
  {
    name: 'India DPDP Act',
    country: 'India',
    region: 'Asia-Pacific',
    year: 2023,
    status: 'enacted',
    themes: ['Data protection', 'Consent', "Children's data"],
    url: 'https://meity.gov.in/',
    summary: `India's Digital Personal Data Protection Act (DPDP Act) 2023 is India's first comprehensive data protection legislation, establishing rights for data principals (individuals) and obligations for data fiduciaries (organisations processing data). It takes a consent-first approach, requiring explicit consent for most personal data processing, with exceptions for legitimate uses. For AI builders, key implications include strict consent requirements for any personal data used in AI training or inference, special protections for children's data, data localisation requirements for sensitive data categories, and breach notification obligations. The Act establishes the Data Protection Board of India as regulator. Implementing rules are still being finalised, which will clarify many operational requirements.`,
    keyProvisions: [
      'Consent required as primary lawful basis for personal data processing',
      'Legitimate uses exceptions: employment, legal compliance, public interest',
      "Children's data: verifiable parental consent required, no tracking or behavioural advertising",
      'Data fiduciary obligations: accuracy, security safeguards, breach notification',
      'Data principal rights: access, correction, erasure, grievance redressal',
      'Significant data fiduciaries: additional obligations including data protection officer, audit',
      'Fines up to ₹250 crore for serious violations',
    ],
    appliesTo: 'Any organisation processing digital personal data of individuals in India, or processing data of Indian residents outside India.',
  },
  {
    name: 'HIPAA (AI applications)',
    country: 'United States',
    region: 'Americas',
    year: 1996,
    status: 'enacted',
    themes: ['Health data', 'Privacy', 'Security', 'US'],
    url: 'https://www.hhs.gov/hipaa/index.html',
    summary: `The Health Insurance Portability and Accountability Act (HIPAA) is the foundational US health data privacy law, and its implications for AI in healthcare are significant and increasingly enforced. HIPAA's Privacy Rule restricts the use and disclosure of Protected Health Information (PHI), while the Security Rule requires administrative, physical, and technical safeguards for electronic PHI. For AI systems processing health data of US patients — including AI diagnostic tools, clinical decision support, and health management apps — HIPAA compliance is mandatory if the organisation is a covered entity or business associate. The HHS Office for Civil Rights has issued guidance specifically on HIPAA and AI, clarifying that AI model training on PHI requires patient authorisation or a valid HIPAA exception.`,
    keyProvisions: [
      'Privacy Rule: restrictions on use and disclosure of PHI without patient authorisation',
      'Security Rule: technical, physical, and administrative safeguards for ePHI',
      'Business Associate Agreements required when PHI is shared with AI vendors',
      'Minimum necessary standard: only the minimum PHI necessary for the purpose may be used',
      'De-identification: properly de-identified data is not PHI and not subject to HIPAA',
      'AI model training on PHI requires authorisation or valid exception (research, treatment)',
      'Breach notification: affected individuals and HHS must be notified of PHI breaches',
    ],
    appliesTo: 'Covered entities (health plans, healthcare providers, clearinghouses) and their business associates that handle Protected Health Information of US patients.',
  },
  {
    name: 'ISO/IEC 23894:2023',
    country: 'International',
    region: 'International',
    year: 2023,
    status: 'standard',
    themes: ['AI risk', 'Risk management'],
    url: 'https://www.iso.org/standard/77304.html',
    summary: `ISO/IEC 23894:2023 provides guidance on AI risk management, offering a systematic and structured approach to identifying, assessing, and treating risks associated with AI systems. It is designed to be used alongside ISO 42001 and aligns with ISO 31000 (general risk management). The standard covers the full AI lifecycle — from design through development, deployment, and decommissioning — and addresses both technical risks (model performance, robustness, security) and non-technical risks (ethical concerns, societal impacts, legal compliance). It provides practical methodologies for risk identification, risk analysis techniques, and risk treatment options specifically tailored to AI systems.`,
    keyProvisions: [
      'AI risk management process: context establishment, risk assessment, risk treatment',
      'Risk identification techniques for AI-specific hazards',
      'Risk analysis: likelihood, consequence, and risk level determination',
      'Risk treatment: modification, sharing, retention, or avoidance',
      'Monitoring and review of AI risks over system lifecycle',
      'Documentation requirements for AI risk management decisions',
    ],
    appliesTo: 'Organisations developing, deploying, or procuring AI systems who need a systematic approach to AI risk management.',
  },
  {
    name: 'IEEE 7000 Series',
    country: 'International',
    region: 'International',
    year: 2021,
    status: 'standard',
    themes: ['Ethical AI', 'Values', 'Design'],
    url: 'https://ethicsstandards.org/',
    summary: `The IEEE 7000 series of standards addresses ethical considerations in autonomous and intelligent systems design. IEEE 7000 (the flagship standard) introduces a process for embedding ethical values into system design from the earliest stages — a concept called "value-based engineering." It provides a structured methodology for identifying the values relevant to a system, assessing how design choices affect those values, and making value-conscious design decisions. Related standards in the series address specific ethical concerns including algorithmic bias (IEEE 7003), data privacy (IEEE 7002), transparency (IEEE 7001), and child and student data governance (IEEE 7004). Together, the series provides a comprehensive toolkit for organisations committed to building AI systems that respect human values and rights.`,
    keyProvisions: [
      'IEEE 7000: Value-based system design process — from values to requirements',
      'IEEE 7001: Transparency in autonomous systems',
      'IEEE 7002: Data privacy process for systems and software engineering',
      'IEEE 7003: Algorithmic bias considerations',
      'IEEE 7004: Standard for child and student data governance',
      'IEEE 7010: Wellbeing metrics for autonomous and intelligent systems',
    ],
    appliesTo: 'System designers and AI developers seeking to embed ethical values and responsible design practices into AI system development.',
  },
  {
    name: 'Brazil AI Bill PL 2338/2023',
    country: 'Brazil',
    region: 'Americas',
    year: 2023,
    status: 'draft',
    themes: ['AI regulation', 'High-risk AI', 'Rights'],
    url: 'https://www25.senado.leg.br/',
    summary: `Brazil's AI Bill (PL 2338/2023) is a comprehensive proposed AI regulation modelled in part on the EU AI Act, establishing a risk-based framework with strong individual rights provisions. It classifies AI systems by risk level, with high-risk systems — including those affecting health, education, employment, credit, and public safety — subject to conformity assessments, transparency requirements, and impact assessments. The Bill establishes a national AI governance authority and creates specific rights for individuals affected by AI decisions, including the right to explanation, human review, and contest. Brazil's LGPD (2020) already provides the data protection baseline, and the AI Bill would layer AI-specific obligations on top.`,
    keyProvisions: [
      'Risk classification: high-risk AI includes health, education, employment, credit decisions',
      'Impact assessments required before deployment of high-risk AI',
      'Transparency: users must be informed when interacting with AI systems',
      'Right to explanation for AI decisions with significant effects',
      'Right to human review of high-risk AI decisions',
      'National AI governance authority established',
      'Liability framework for harm caused by AI systems',
    ],
    appliesTo: 'Organisations developing or deploying AI systems in Brazil or whose AI systems affect Brazilian residents.',
  },
  {
    name: 'UAE ADGM AI Guidance',
    country: 'UAE',
    region: 'Middle East',
    year: 2023,
    status: 'guidelines',
    themes: ['Financial AI', 'FinTech', 'Governance'],
    url: 'https://www.adgm.com/',
    summary: `The Abu Dhabi Global Market (ADGM) AI Guidance provides specific expectations for the use of AI in financial services within the ADGM financial free zone. It applies to all ADGM-registered financial institutions and FinTech companies using AI in regulated activities. The guidance covers model risk management, algorithmic trading oversight, AI explainability in credit decisions, and governance requirements for AI systems. ADGM is positioning itself as a leading FinTech hub for the MENA region, and its AI guidance reflects a pragmatic, innovation-friendly approach while maintaining robust consumer protection standards. The guidance is informed by international standards including the FSB's AI and machine learning in financial services report.`,
    keyProvisions: [
      'Model risk management framework for AI/ML models in financial services',
      'AI governance: board and senior management accountability for AI risk',
      'Explainability requirements for AI-driven credit and underwriting decisions',
      'Algorithmic trading oversight and controls',
      'Data quality and bias assessment requirements',
      'Third-party AI vendor due diligence requirements',
      'Incident reporting for AI system failures affecting customers',
    ],
    appliesTo: 'Financial institutions and FinTech companies registered with ADGM and using AI in regulated financial services activities.',
  },
  {
    name: 'UK ICO AI Guidance',
    country: 'United Kingdom',
    region: 'Europe',
    year: 2023,
    status: 'guidelines',
    themes: ['AI transparency', 'Automated decisions', 'UK GDPR'],
    url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/',
    summary: `The UK Information Commissioner's Office (ICO) has published comprehensive guidance on using AI in compliance with UK GDPR. This guidance addresses the specific data protection challenges posed by AI systems, including how to lawfully process personal data for AI training, how to meet transparency obligations when using AI, how to handle automated decision-making under Article 22 UK GDPR, and how to conduct Data Protection Impact Assessments for AI systems. The ICO has also published an AI and data protection risk toolkit to help organisations assess their AI governance maturity. Given the UK's post-Brexit approach of applying existing regulatory frameworks to AI rather than introducing a new AI Act, the ICO's guidance is the primary regulatory reference for AI data protection compliance in the UK.`,
    keyProvisions: [
      'Lawful basis for AI training on personal data: guidance on legitimate interests assessment',
      'Transparency in AI: privacy notices must explain AI use in accessible language',
      'Automated decision-making (Art. 22 UK GDPR): when it applies and how to comply',
      'DPIA guidance for AI systems: when required and how to conduct',
      'Fairness in AI: how to assess and mitigate discriminatory outcomes',
      'AI auditing: guidance on accountability and governance for AI systems',
    ],
    appliesTo: 'Organisations in the UK or processing personal data of UK residents who use AI systems in their operations.',
  },
  {
    name: 'NIST Privacy Framework',
    country: 'International',
    region: 'International',
    year: 2020,
    status: 'standard',
    themes: ['Privacy', 'Risk', 'Data governance'],
    url: 'https://www.nist.gov/privacy-framework',
    summary: `The NIST Privacy Framework is a voluntary tool that helps organisations identify and manage privacy risks in their systems, products, and services — including AI systems. Structured around five core functions (Identify-P, Govern-P, Control-P, Communicate-P, Protect-P), it provides a common language for privacy risk management that complements the NIST Cybersecurity Framework. For AI builders, it is particularly useful for systematically identifying privacy risks in data collection, AI training, model inference, and output generation, and for implementing appropriate controls. The framework aligns with major privacy regulations globally and can be used to demonstrate privacy accountability to regulators and customers.`,
    keyProvisions: [
      'Identify-P: inventorying data processing and identifying privacy risks',
      'Govern-P: organisational privacy policies, values, and risk tolerance',
      'Control-P: data processing policies that enable individuals to exercise privacy interests',
      'Communicate-P: communicating privacy practices to individuals and stakeholders',
      'Protect-P: data protection activities, including security controls',
    ],
    appliesTo: 'Any organisation developing or deploying systems that process personal data, including AI systems. Particularly useful as a complement to NIST AI RMF for privacy risk management.',
  },
  {
    name: 'ISO/IEC 24028:2020',
    country: 'International',
    region: 'International',
    year: 2020,
    status: 'standard',
    themes: ['AI trustworthiness', 'Bias', 'Robustness'],
    url: 'https://www.iso.org/standard/77608.html',
    summary: `ISO/IEC 24028:2020 provides an overview of trustworthiness in artificial intelligence, defining key concepts and properties that characterise trustworthy AI systems. It covers the full spectrum of AI trustworthiness attributes including availability, resiliency, reliability, accuracy, safety, security, privacy, and fairness. The standard is particularly useful for organisations that need a comprehensive vocabulary and conceptual framework for discussing AI trustworthiness with stakeholders, regulators, and customers. It provides the definitional foundation that other AI standards and regulations build upon, making it an important reference for anyone working in AI governance.`,
    keyProvisions: [
      'Definitions of AI trustworthiness attributes: availability, resiliency, reliability, accuracy, safety, security, privacy, fairness, explainability',
      'Threats to AI trustworthiness: adversarial attacks, data poisoning, model theft',
      'Bias types in AI: data bias, algorithmic bias, cognitive bias',
      'Transparency and explainability concepts for AI systems',
      'AI system testing and evaluation approaches for trustworthiness',
    ],
    appliesTo: 'AI developers, deployers, and governance professionals who need a comprehensive framework for understanding and communicating AI trustworthiness.',
  },
  {
    name: 'NIST AI 100-2',
    country: 'International',
    region: 'International',
    year: 2024,
    status: 'standard',
    themes: ['Adversarial ML', 'Security', 'Robustness'],
    url: 'https://airc.nist.gov/Docs/2',
    summary: `NIST AI 100-2 (Adversarial Machine Learning: A Taxonomy and Terminology) provides comprehensive guidance on the security threats facing AI systems and the mitigations available to address them. It categorises adversarial attacks across four AI paradigms — predictive AI, generative AI, reinforcement learning, and multi-agent systems — and provides detailed guidance on evasion attacks, poisoning attacks, privacy attacks, and abuse attacks. For AI builders, this document is essential reading for understanding the security threat landscape and designing AI systems with appropriate defences. It is increasingly referenced by regulators and enterprise security teams as a baseline for AI security assessment.`,
    keyProvisions: [
      'Taxonomy of adversarial attacks: evasion, poisoning, privacy, abuse attacks',
      'Attack descriptions for predictive AI, generative AI, and reinforcement learning',
      'Mitigation strategies for each attack category',
      'Guidance on adversarial robustness testing and red-teaming',
      'Privacy attacks: model inversion, membership inference, model extraction',
      'Supply chain attacks on AI models and training data',
    ],
    appliesTo: 'AI developers and security professionals responsible for assessing and mitigating security risks in AI systems.',
  },
  {
    name: 'South Korea PIPA',
    country: 'South Korea',
    region: 'Asia-Pacific',
    year: 2020,
    status: 'enacted',
    themes: ['Data protection', 'AI transparency', 'Automated decisions'],
    url: 'https://www.pipc.go.kr/',
    summary: `South Korea's Personal Information Protection Act (PIPA), significantly amended in 2020 and 2023, is one of the most comprehensive data protection laws in Asia-Pacific. It includes specific provisions on automated decision-making that are directly relevant to AI systems. Under PIPA, individuals have the right to refuse automated decisions that significantly affect their rights or interests, and the right to request human review and explanation of such decisions. The 2023 amendments introduced stronger protections for sensitive personal information and increased the role of the Personal Information Protection Commission (PIPC). South Korea's approach to AI governance is generally innovation-friendly while maintaining strong individual rights protections.`,
    keyProvisions: [
      'Automated decision-making: right to refuse, right to explanation, right to human review',
      'Sensitive personal information: biometric, health, sexual orientation — enhanced protection',
      'Pseudonymisation: allowed for statistical, research, and public interest purposes',
      'Cross-border transfer: adequate protection or safeguards required',
      'Personal Information Protection Commission: strong enforcement authority',
      'Data breach notification: within 72 hours to the PIPC',
    ],
    appliesTo: 'Any organisation processing personal information of individuals in South Korea, including overseas organisations whose services are directed at South Korean users.',
  },
  {
    name: 'Ghana National AI Policy',
    country: 'Ghana',
    region: 'Africa',
    year: 2023,
    status: 'enacted',
    themes: ['AI strategy', 'Ethics', 'Inclusive AI'],
    url: 'https://moc.gov.gh/',
    summary: `Ghana's National AI Policy (2023) establishes the country's strategic framework for AI development and governance, with a strong emphasis on inclusive AI that serves Ghana's development priorities. The policy creates a governance structure for AI oversight, establishes ethical principles for AI deployment, and outlines priority sectors including agriculture, health, education, and financial inclusion. Ghana is notable for integrating AI governance with its broader digital economy strategy and for emphasising that AI should serve local needs rather than simply adopting Western AI frameworks. The policy complements Ghana's Data Protection Act and provides guidance for both public and private sector AI deployment.`,
    keyProvisions: [
      'National AI governance structure with multi-stakeholder oversight',
      'Six AI ethics principles: fairness, transparency, accountability, safety, privacy, inclusivity',
      'Priority sectors: agriculture, health, education, financial services, public administration',
      'AI skills development and local AI research capacity building',
      'Public procurement guidelines for AI systems in government',
      'Guidance on AI for financial inclusion and serving unbanked populations',
    ],
    appliesTo: 'Organisations deploying AI systems in Ghana, particularly those working in priority development sectors or providing AI systems to the Ghanaian government.',
  },
  {
    name: 'Mauritius Data Protection Act',
    country: 'Mauritius',
    region: 'Africa',
    year: 2017,
    status: 'enacted',
    themes: ['Data protection', 'Privacy', 'GDPR-aligned'],
    url: 'https://dataprotection.govmu.org/',
    summary: `Mauritius's Data Protection Act (2017) is a GDPR-aligned data protection law that has positioned Mauritius as one of Africa's most robust data governance jurisdictions. The Act established the Data Protection Office as regulator and introduced a comprehensive framework of data subject rights and controller obligations. Mauritius also published Africa's first national AI strategy in 2018, demonstrating early commitment to AI governance. For AI builders, the Act imposes standard data protection obligations including lawful basis requirements, data subject rights, security obligations, and restrictions on international transfers. Mauritius's GDPR-alignment makes it an attractive jurisdiction for organisations operating across both African and European markets.`,
    keyProvisions: [
      'Data Protection Office: established as independent regulator',
      'Lawful basis for processing: consent, contract, legal obligation, legitimate interests',
      'Data subject rights: access, rectification, erasure, objection',
      'Security obligations: appropriate technical and organisational measures',
      'International transfers: adequacy or appropriate safeguards required',
      'Data breach notification to the Data Protection Office',
    ],
    appliesTo: 'Organisations processing personal data in Mauritius or processing data of Mauritius residents.',
  },
  {
    name: 'Uganda DPDPA',
    country: 'Uganda',
    region: 'Africa',
    year: 2019,
    status: 'enacted',
    themes: ['Data protection', 'Registration', 'Rights'],
    url: 'https://www.pdpo.go.ug/',
    summary: `Uganda's Data Protection and Privacy Act (DPDPA) 2019 established the Personal Data Protection Office (PDPO) as Uganda's data protection regulator. It provides a comprehensive framework for data protection rights and obligations, and was one of the earlier African countries to enact standalone data protection legislation. For AI builders operating in Uganda or processing data of Ugandan residents, key requirements include registration with the PDPO, obtaining consent or establishing another lawful basis for processing, implementing security measures, and respecting data subject rights. Uganda has a growing technology sector and the PDPO has been developing its enforcement capacity since 2021.`,
    keyProvisions: [
      'Personal Data Protection Office (PDPO) established as regulator',
      'Data collector and data processor registration requirements',
      'Lawful basis for processing: consent, contract, legal obligation, public interest',
      'Data subject rights: access, rectification, erasure, objection',
      'Security measures: appropriate technical and organisational safeguards',
      'Cross-border transfer restrictions: adequate protection required',
    ],
    appliesTo: 'Organisations processing personal data in Uganda or processing data of Ugandan residents.',
  },
  {
    name: 'Morocco Data Protection Law 09-08',
    country: 'Morocco',
    region: 'Africa',
    year: 2009,
    status: 'enacted',
    themes: ['Data protection', 'CNDP', 'Registration'],
    url: 'https://www.cndp.ma/',
    summary: `Morocco's Law No. 09-08 on the Protection of Individuals with regard to Personal Data Processing established the National Commission for the Control of Personal Data Protection (CNDP) as Morocco's data protection authority. The law was an early African adoption of European-style data protection principles, reflecting Morocco's close relationship with the EU. For AI builders, the law requires registration of personal data processing with the CNDP for certain categories, establishes individual rights to access and correct personal data, and restricts international data transfers. Morocco's Digital Morocco 2030 strategy includes AI governance pillars that are beginning to translate into more specific AI guidance.`,
    keyProvisions: [
      'CNDP established as independent data protection authority',
      'Prior declaration or authorisation required for certain data processing activities',
      'Individual rights: access, rectification, opposition',
      'Sensitive data: health, biometric, political, religious data requires specific authorisation',
      'International transfer restrictions: Morocco or adequate protection required',
      'Digital Morocco 2030: AI governance strategy in development',
    ],
    appliesTo: 'Organisations processing personal data in Morocco or processing data of Moroccan residents.',
  },
  {
    name: 'Egypt Personal Data Protection Law',
    country: 'Egypt',
    region: 'Africa',
    year: 2020,
    status: 'enacted',
    themes: ['Data protection', 'Privacy', 'Sensitive data'],
    url: 'https://www.mcit.gov.eg/',
    summary: `Egypt's Personal Data Protection Law (No. 151 of 2020) established Egypt's first comprehensive data protection framework and created the Personal Data Protection Centre as the regulatory authority. The law applies to all processing of personal data of Egyptian residents, whether by Egyptian or foreign organisations. For AI builders, key requirements include obtaining consent or establishing a lawful basis for processing, implementing security measures, restricting international data transfers, and complying with data subject rights. Egypt's National AI Strategy (2022) additionally outlines sectoral AI governance expectations particularly for health, agriculture, and public administration. Egypt is one of Africa's largest digital economies and the regulatory environment for AI is evolving rapidly.`,
    keyProvisions: [
      'Personal Data Protection Centre established as regulator',
      'Consent as primary lawful basis; other bases available for specific purposes',
      'Sensitive data: health, financial, biometric data requires explicit consent',
      'Data subject rights: access, rectification, erasure, restriction, portability',
      'Security measures: appropriate technical and organisational safeguards',
      'International transfer restrictions: Egypt or adequate protection',
      'Data breach notification obligations',
    ],
    appliesTo: 'Any organisation processing personal data of Egyptian residents, whether based in Egypt or overseas.',
  },
  {
    name: 'Rwanda Data Protection Law',
    country: 'Rwanda',
    region: 'Africa',
    year: 2021,
    status: 'enacted',
    themes: ['Data protection', 'Privacy', 'AI governance'],
    url: 'https://www.dataguidance.com/notes/rwanda-data-protection-overview',
    summary: `Rwanda's Law No. 058/2021 on the Protection of Personal Data and Privacy established a comprehensive data protection framework and created the Rwanda Information Society Authority (RISA) as the implementing body. The law is aligned with international best practices and supports Rwanda's ambition to be a leading digital economy in Africa. For AI builders, it establishes lawful basis requirements, data subject rights, security obligations, and cross-border transfer restrictions. Combined with Rwanda's National AI Policy (2023), Rwanda offers one of Africa's most complete regulatory environments for responsible AI development — with both data protection and AI-specific governance in place.`,
    keyProvisions: [
      'Rwanda Information Society Authority (RISA) as implementing body',
      'Lawful basis: consent, contract, legal obligation, vital interests, public interest',
      'Data subject rights: access, rectification, erasure, restriction, portability, objection',
      'Data Protection Officer required for certain processing activities',
      'Security measures: risk-proportionate technical and organisational safeguards',
      'Cross-border transfers: adequate protection or appropriate safeguards required',
    ],
    appliesTo: 'Organisations processing personal data in Rwanda or processing data of Rwandan residents.',
  },
];